---
title: "COVID-19 analysis for Ghana"
description: |
  Welcome to our new blog, This is the anlaysis of COVID-19 for Ghana, mainly focusing on the confirmed case numbers. Hope you can enjoy reading what I share and display!
author:
  - name: Yiwen Zhang 

date: 02-09-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(coronavirus)
library(plotly)
library(lubridate)
library(knitr)
library(dplyr)
library(htmltools)
library(kableExtra)
data("coronavirus")

```

```{r filterdata}
covid_ghana <- coronavirus %>%
  filter(country == "Ghana") 
```

```{r pivotwider}
covid_ghana_wider <- covid_ghana %>%
  select("date","country","type","cases") %>%
group_by(type) %>%
  pivot_wider(names_from = "type", values_from = "cases")
```

```{r summary}
summary_ghana <- covid_ghana %>%
  summarise(avg_death = mean(death), avg_confirmed = mean(confirmed), avg_recovered = mean(recovered)) %>%
  pivot_longer(c("avg_death", "avg_confirmed","avg_recovered"), names_to = "type", values_to = "avg") 
```

```{r table1, echo=FALSE}
kable(summary_ghana,
      booktabs = TRUE, 
      caption = "The average death,confirmed and recovered cases in Ghana") %>%
  kable_styling(bootstrap_options = c("striped", "hover"), 
                full_width = F,
                latex_options = c("hold_position"))
```

```{r COVID19cases, echo=FALSE}
p1 <- covid_ghana %>%
  ggplot(aes(x = date,
             color = type,
             group = type)) +
  geom_line(aes(y = cases))+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())

ggplotly(p1)
``` 


# Data description


# Data Analysis