---
title: "COVID-19 analysis for Russia"
description: |
  Welcome to my new blog, this is the anlaysis of COVID-19 for Russia, mainly focusing on exploring case numbers. Hope you can enjoy reading what I share and display!
author:
  - name: Yiwen Zhang 
    url: https://thirsty-pasteur-78571a.netlify.app/
date: 09-03-2020
categories:
  - COVID-19 Ghana
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
    self_contained: false
preview: COVID-19.png
bibliography: references.bib
biblio-style: authoryear-comp

---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(coronavirus)
library(tidyverse)
library(DT)
library(formattable)
library(plotly)
library(lubridate)
library(knitr)
library(dplyr)
library(reactable)
library(kableExtra)
library(sparkline)
library(htmltools)
library(leaflet)
library(ggplot2)
```

```{r}
russia_case <- read_csv("_posts/blog2/data-Russia/covid19-russia-cases-scrf.csv")
region_info <- read_csv("_posts/blog2/data-Russia/regions-info.csv")
region_ventilator <- read_csv("_posts/blog2/data-Russia/regions-ventilators.csv")
```

```{r}
#delete the column won't be used and drop NA
russia_case <- russia_case %>%
  select(-`Region/City`)

region_ventilator <- region_ventilator %>%
  select(-`Region`) 
 
region_ventilator <- region_ventilator %>%
  drop_na()

region_info_new <- region_info %>%
  select(`Region_eng`,`Latitude`,`Longitude`) 
  
```

```{r}
#rename the column name
russia_case <- russia_case %>%
  setNames(c("Date","Region","Region_ID","DConf","DDeath","DRec","Conf","Death","Rec"))

region_info_new <- region_info_new %>%
  setNames(c("Region","Latitude","LongitudeD"))
```

```{r}
#join the data
covid_location = left_join(x = russia_case, y = region_info_new, by="Region")
```



