---
title: "Review for 'COVID19usa'"
description: |
  This is the review for package 'COVID19usa', which contains the context and a check list.
author:
  - name: Yiwen Zhang 
  
date: 10-28-2020
categories:
  - Package Review
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
    self_contained: false
preview: covid19usa.png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

The package I reviewed is named "covid19usa", which is created by Brendi Ang. The goal of the "covid19usa" package is to provide an embedded interactive R Shiny web application for key data visualization of Covid-19 cases and testing efficiency across the U.S states. 

And it contains two main functions, which are refactored from user-interface and sever-side logic of the shiny app embedded inside the package:

- ui_input() : Creates reactive input for Shiny app.
- us_pop_ests : Provides the dataset for the estimated population by U.S county, primarily used for relational joins.

What's more, it also provides the relevant datasets to run this shiny app and for further use. One is the dataset for the Confirmed Covid-19 Cases and Deaths by States in the U.S, reported by The New York Times, from 2020-01-22 to 2020-10-07. Another one is the US map data for states.

# What I expect

On the first I look into this package, I thought it should first provide the shiny app on COVID-19, then relevant datasets to run the app and the functions that can be used in a further stage smoothly. Also, I expect there will be a detailed instruction and the documentation inside both package and shiny app will be logical and concise enough, so I can have a smoother experience on referring this package.

When I actually reviewing this package, I found it an excellent package with complete structure and clear logic. It did most of what I expected. I can get the data easily, run the function smoothly, and most importantly, the shiny app, can be launched up successfully. 

When exploring the shiny app, I found the UI interface is quite visual appealing, which brings me a good experience. And I can get to know the COVID-19 condition of USA easily by controlling the input of date and state. The "About" page is also very fluent and clear, from which I can quickly get to know the motivation and the creator of this app. 

# What I suggest

Although this package is amazing, I have some suggestions that are mainly for the shiny app.

First, I notice that after opening the app, I must set the input options and click the button "show the trend" first, before the graph appear. My suggestion is that it's better to display a defauLt graph at the beginning, which I believe will be more visual appealing! In addition, after setting the options, it is better to directly generate graphs automatically without clicking the button again, which will be more convenient and bring better visual experience to users.

What's more, there is only one type distribution map of COVID-19 cases (confirmed cases), which is quite sensible. After all, people are most concerned about the diagnosis of the epidemic situation. However, it will be more comprehensive if the death and recovered cases can be added to reflect the cure and control effect of different regions.

At last, the only thing for the package is that it's best to document all the packages needed to run the shiny app in the README file, because I found it not completely written now, which led me to get remind of the lack of packages by R Studio when running shiny, and got interrupted several times before success.

# What I learned

I learned a lot by exploring this package. 

First of all, in terms of structure, I should cover the content as much as possible like the author. For example, including the contact information of the creator in the READEME part, so that users can report bugs or errors in time.

Additionally, it's the interactive table. The author only selected one day's case as the display, which well controlled the amount of data in the table. And my biggest mistake is just on this issue. I did not filter the table data, so it seems that there is no focus and too much data in the table.

Finally, I also realize that shiny dashboard is more beautiful and user-friendly, and I'll try to apply it in another assignment I'm working on.

Overall, the author of "covid19usa" did do an excellent job, and the package is really an outstanding work. I feel so delighted when exploring that. Thanks for the hard working of Brendi Ang. : )


# Appendix

## Package Review

*Please check off boxes as applicable, and elaborate in comments below.*

#### Documentation 

The package includes all the following forms of documentation: 

- [x] **Installation instructions:** for the package is found in README. 

The instruction is clearly documented in READEME, but if there also includes all the packages needed to run the app, it's much better!


- [x] **Vignette(s)** demonstrating major functionality that runs successfully locally.

The vignettes is well structured and has a detailed introduction to the package and the use of the shiny app.


- [x] **Function Documentation:** for all exported functions in R help 

The function documentation is clearly written and can be easily understood by users.


- [x] **Examples** for all exported functions in R Help that run successfully locally.

There are enough examples for the use of functions and can run successfully locally.


#### Functionality 

- [x] **Installation:** Installation succeeds as documented.

When installing the package, it succeeded, despite waiting for a while.


- [x] **Functionality:** Any functional claims of the software been confirmed.

The function of the function in this package was verified when I ran it.


- [x] **Automated tests:** Unit tests cover essential functions of the package and a 
reasonable range of inputs and conditions. All tests pass on the local machine.

All the tests on the function are intuitive and representative, and they all passed successfully on my local computer.

