---
title: "Review for Shiny App on COVID-19 Analysis"
description: |
  This is the review for my previous shiny app on COVID-19 global analysis. In this review, I will introduce the content of my app , then show both where it's done well, where it's worth improving, and what I might add next time. Hope you can enjoy when reading!
author:
  - name: Yiwen Zhang 
    url: https://thirsty-pasteur-78571a.netlify.app/
date: 10-12-2020
categories:
  - Shiny App Review
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
    self_contained: false
preview: review.jpg
bibliography: references.bib
biblio-style: authoryear-comp
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

My shiny app is an interactive web app built straight from R, with the using of shiny package[@shiny], and some other packages like tidyverse[@tidyverse], ggplot2[@ggplot2], plotly[@plotly], leaflet[@leaflet], DT[@DT], highcharter[@highcharter] and shinythemes[@shinythemes]. And the main title of this app is COVID-19 Global Analysis. It consists of four main pages.

- The first page contains the map that displays the distribution of confirmed cases, recovered cases and deaths. And users can determine which type of case to explore by selecting from the sidebar on the left. In this way, not only can users know the geographical distribution of the cases, but also grasp a general view of this epidemic. 

  *The United States has the largest number of confirmed cases and deaths, which shows that the United States is the most    serious epidemic area in the world. India has the largest number of cured cases, with the cure rate reaching to around    81.3%, which indicates that India's medical conditions are worthy of recognition in this case.*

- Then it comes to the second page, which includes a interactive line chart on the trend of the case changing over time. After having a macro understanding of the COVID-19 through the map, we narrow the geographical scope to different states or provinces in each country, and further observe the changes of this epidemic over time among different regions. 
There are three lines in this chart. The yellow line represents the confirmed case, the green line represents the recovered case and the red line represents the deaths. 

  *It can be seen that in most regions, the number of deaths has remained at a low growth level, while the number of         confirmed cases and cured cases has increased to varying degrees*

- If we want more specific numeric results, then wen can refer to the interactive table in the third page. When inputting the key word, the results you want to explore will show in the table.

- The last page consists of three sub-pages, which are "About", "Instruction" and "Acknowledgements".
  + The "About" page is about the purpose and the creator of the app
  + The "Instruction" is about the detailed steps to run this app and the session information.
  + The "Acknowledgements" is about the thanks for the data source and the packages I used in this app, as well as the        references.

# Self Review

- Firstly, I think what I did well is that I use a quite visual appealing map to show the distribution of the case, which is also a new point for me to learn about the "highcharter" graph. And I add enough text inside the app to guide the user how to use each section, as well as writing some explanation under the plot to summarize what can be learned from that to make my app more easy-reading. What's more, I try to make the structure of this app more complete as much as possible.

- However, there are some points that I can improve. The first thing is the appearance of my app, although I tried my best to beautify it for a long time, the results showed that I could make it further to my ideal appearance to improve the user experience. The second thing is about the interactive table, it also needs to be optimized. And the plotly graph, I think its appearance is not very ideal either. The last point is the "more" page, the typography in this page also needs to be improved.

- As for the things that can be added to my app, I would like to add two tab panels in the navbar, one is linked to my github website, another is a link used to email me. In this way, if there is any wrong or users want to communicate with me, they can contact me conveniently. In addition, some interesting pictures can be added inside the app to make it more fascinating.

- I originally wanted to add the infection rate and diagnosis rate of the COVID-19 in the total population. However, due to the limitation of the data, that is, there is no population in each state/province in the data. Even if I go to search the population data of states/provinces separately, it is difficult to match them together. What's more, population data in small regions of some small countries is hard to find as well. Another thing is about the interactive table, I think it's possible to add more complex elements, but I haven't mastered it yet.


Overall, I benefited a lot from this assignment. I also learned new charts and the way to make shiny. I think I did well on the whole, basically met the requirements, and also took my own ideas. However, it is still a simple and simple achievement. There are many places worth further improvement, making it more refined and complete, and also enabling users to have better experience.
